// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CollapseList: typeof import('./src/components/CollapseList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCart2: typeof import('./src/components/icons/bootstrap-icon/IconCart2.vue')['default']
    IconCommunity: typeof import('./src/components/icons/intro/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/intro/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/intro/IconEcosystem.vue')['default']
    IconPeopleCircle: typeof import('./src/components/icons/bootstrap-icon/IconPeopleCircle.vue')['default']
    IconSupport: typeof import('./src/components/icons/intro/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/intro/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
